name: Hello World

on:

  push:
    branches: [ "main" ]  
    
  workflow_dispatch:
      inputs:
       user_selected_env:      # ‚Üê INPUT: User chooses at runtime
        description: 'Select environment'
        required: true
        default: 'staging'
 

jobs:
  say-hello-inline-bash:
    runs-on: ubuntu-24.04
    env:
      MY_VAR: "Job Value"

    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"

      - name: Convert INPUT to ENV VAR
        env:
          # Convert user input to environment variable
          TARGET_ENVIRONMENT: ${{ github.event.inputs.user_selected_env }}
        run: |
          # NOW it's an environment variable!
          echo "Target environment: $TARGET_ENVIRONMENT"

      - name: Print Job Scope
        run: echo "$MY_VAR" # Output: "Job Valuejj"    
          